Walkhub/Walkhub-Server

.github/CODEOWNERS

PR 작성시 자동으로 Reviewer를 추가해주는 CODEOWNERS 파일 작성
Closes #6

🔀 :: CODEOWNERS 파일 추가

---

src/main/java/com/walkhub/walkhub/domain/user/domain/Badge.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/BadgeRepository.java

🔀 :: (#14) badge entity 생성

---

src/main/java/com/walkhub/walkhub/domain/user/domain/Badge.java

🔀 :: (#33) 대문자 -> 소문자

---

src/main/java/com/walkhub/walkhub/domain/user/domain/Group.java
src/main/java/com/walkhub/walkhub/domain/user/domain/GroupId.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/GroupRepository.java

🔀 :: (#9) group entity

---

src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationList.java
src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationListId.java
src/main/java/com/walkhub/walkhub/domain/notification/domain/repository/NotificationListRepository.java

🔀 :: (#20) notification_list entity

---

build.gradle
src/main/java/com/walkhub/walkhub/domain/teacher/domain/AuthCode.java
src/main/java/com/walkhub/walkhub/domain/teacher/domain/repository/AuthCodeRepository.java

🔀 :: (#21) teacher_auth_code entity

---

build.gradle
src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationList.java
src/main/java/com/walkhub/walkhub/domain/notification/domain/repository/NotificationRepository.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/BadgeRepository.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/GroupRepository.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/SchoolRepository.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
src/main/java/com/walkhub/walkhub/domain/user/domain/type/HealthInfo.java
src/main/java/com/walkhub/walkhub/domain/user/domain/type/Sex.java
src/main/java/com/walkhub/walkhub/global/enums/Authority.java

🔀 :: (#10) user-entity

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/ExerciseAnalysis.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java

 🔀 :: (#25) ExerciseAnalysis 엔티티 생성 

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java

🔀 :: (#23) challenge entity

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/CertifyingShot.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/CertifyingShotRepository.java

🔀 :: (#27) certifying_shot entity

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/Location.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/LocationId.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/LocationRepository.java
src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationListId.java

🔀 :: (#28) location entity

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/ChallengeStatus.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/ChallengeStatusId.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java

26 challenge_status entity

---

src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepository.java
src/main/java/com/walkhub/walkhub/domain/notice/domain/type/Scope.java

🔀 :: (#22) notice entity

---

src/main/java/com/walkhub/walkhub/global/error/ErrorResponse.java
src/main/java/com/walkhub/walkhub/global/error/GlobalExceptionHandler.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
src/main/java/com/walkhub/walkhub/global/error/exception/WalkhubException.java

🔀 :: (#48) global exception handler

---

build.gradle
src/main/java/com/walkhub/walkhub/infrastructure/sms/SmsUtil.java
src/main/java/com/walkhub/walkhub/infrastructure/sms/coolsms/CoolSms.java
src/main/java/com/walkhub/walkhub/infrastructure/sms/coolsms/CoolSmsProperties.java
src/main/resources/application.yml

🔀 :: (#55) 전화번호 인증 util

---

src/main/java/com/walkhub/walkhub/domain/teacher/domain/TeacherAuthCode.java
src/main/java/com/walkhub/walkhub/domain/teacher/domain/repository/AuthCodeRepository.java
src/main/java/com/walkhub/walkhub/domain/teacher/domain/repository/TeacherAuthCodeRepository.java
src/main/java/com/walkhub/walkhub/domain/user/domain/UserAuthCode.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserAuthCodeRepository.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserAuthCodeRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserAuthCodeService.java
src/main/java/com/walkhub/walkhub/global/async/AsyncConfig.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
src/main/java/com/walkhub/walkhub/global/web/WebMvcConfig.java
src/main/java/com/walkhub/walkhub/infrastructure/sms/coolsms/CoolSms.java
src/main/java/com/walkhub/walkhub/infrastructure/sms/coolsms/CoolSmsProperties.java

🔀 :: (#56) 전화번호 인증(회원가입) API

---

src/main/java/com/walkhub/walkhub/domain/auth/domain/RefreshToken.java
src/main/java/com/walkhub/walkhub/domain/auth/domain/repository/RefreshTokenRepository.java
src/main/java/com/walkhub/walkhub/domain/auth/exception/PasswordNotMatchException.java
src/main/java/com/walkhub/walkhub/domain/auth/prsentation/AuthController.java
src/main/java/com/walkhub/walkhub/domain/auth/prsentation/dto/request/SignInRequest.java
src/main/java/com/walkhub/walkhub/domain/auth/prsentation/dto/response/UserTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#60) 사용자 로그인 API

---

src/main/java/com/walkhub/walkhub/domain/user/exception/UnauthorizedUserAuthCodeException.java
src/main/java/com/walkhub/walkhub/domain/user/exception/UserAuthCodeNotFoundException.java
src/main/java/com/walkhub/walkhub/domain/user/exception/UserExistsException.java
src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#57) user signup

---

src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryMyPageResponse.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
src/main/java/com/walkhub/walkhub/global/exception/CredentialsNotFoundException.java
src/main/java/com/walkhub/walkhub/global/security/auth/AuthDetails.java

유저 프로필조회와 공통되는 부분이 많아 머지된후에 리팩토링할 예정입니다

🔀 :: (#65) 마이페이지 조회 api

---

src/main/java/com/walkhub/walkhub/domain/auth/domain/RefreshToken.java
src/main/java/com/walkhub/walkhub/domain/auth/domain/repository/RefreshTokenRepository.java
src/main/java/com/walkhub/walkhub/domain/auth/exception/RefreshTokenNotFoundException.java
src/main/java/com/walkhub/walkhub/domain/auth/prsentation/AuthController.java
src/main/java/com/walkhub/walkhub/domain/auth/prsentation/dto/response/UserAccessTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/auth/service/TokenRefreshService.java
src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
src/main/java/com/walkhub/walkhub/global/security/jwt/JwtTokenProvider.java

 🔀 :: (#68) Refresh Token API

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
src/main/java/com/walkhub/walkhub/domain/user/service/UpdateUserInfoService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#66) 내 정보 수정 API

---

src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/request/CreateChallengeRequest.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/CreateChallengeService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#76) 챌린지 생성 API 

---

src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserAccessTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/auth/service/TokenRefreshService.java

 🔀 :: 패키지명 오타 수정

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/InputHealthInformationRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#61) 건강 정보 입력 API

---

src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
src/main/java/com/walkhub/walkhub/global/exception/SaveImageFalseException.java

🔀 :: (#95) SaveImageFalse ErrorCode 수정

---

src/main/resources/application.yml

🔀 :: (#92) Graceful shutdown 설정

---

.gitignore
src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationListId.java
src/main/java/com/walkhub/walkhub/infrastructure/fcm/CoolNotification.java
src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java

🔀 :: (#91) fcm initialize setting

---

build.gradle
src/main/java/com/walkhub/walkhub/WalkhubApplication.java
src/main/resources/application.yml

🔀 :: (#99) Spring Batch 설정

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/CreateExerciseResponse.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/CreateExerciseService.java

🔀 :: (#103) 기록 측정 시작(운동) api

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
src/main/java/com/walkhub/walkhub/domain/challenge/exception/AlreadyParticipatedException.java
src/main/java/com/walkhub/walkhub/domain/challenge/exception/ChallengeNotFoundException.java
src/main/java/com/walkhub/walkhub/domain/challenge/exception/InvalidScopeException.java
src/main/java/com/walkhub/walkhub/domain/challenge/facade/ChallengeFacade.java
src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#107) 챌린지 참여

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/UserRank.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepository.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserListResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserSearchResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java

🔀 :: (#100) 유저 조회하기 API

---

build.gradle

🔀 :: (#119) QueryDSL 세팅

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/ChallengeParticipantsElement.java
src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/ChallengeParticipantsListResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantsListService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java

🔀 :: (#116) 챌린지 참여자 목록보기

---

src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/request/CreateChallengeRequest.java

🔀 :: (#124) 챌린지 생성 Request @NotBlank -> @NotNull

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdatePasswordRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/UpdatePasswordService.java

🔀 :: (#135) 유저 비밀번호 변경

---

src/main/java/com/walkhub/walkhub/domain/exercise/exception/ExerciseNotFoundException.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/FinishExerciseRequest.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/FinishExerciseService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#129) 운동 기록 측정 종료

---

Dockerfile
build.gradle

🔀 :: (#137) Docker Image Push

---

build.gradle

🔀 :: (#140) javaSDK 의존성 수정

---

src/main/java/com/walkhub/walkhub/domain/user/domain/type/HealthInfo.java

🔀 :: (#146) @Digits -> @Column로 수정

---

src/main/java/com/walkhub/walkhub/domain/user/domain/repository/SchoolRepository.java
src/main/java/com/walkhub/walkhub/domain/user/exception/SchoolNotFoundException.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#144) signup school name 추가

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateSchoolInfoRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java

🔀 :: (#117) modify school info

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/DeleteClassService.java
src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
src/main/java/com/walkhub/walkhub/domain/user/service/JoinGroupService.java

🔀 :: (#143) 반 삭제하기

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/VerificationCodeResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/VerificationCodeService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserAuthCodeService.java
src/main/java/com/walkhub/walkhub/global/utils/code/RandomCodeUtil.java

🔀 :: (#152) teacher verification code

---

src/main/java/com/walkhub/walkhub/domain/notice/exception/NoticeNotFoundException.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
src/main/java/com/walkhub/walkhub/domain/notice/service/DeleteNoticeService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#157) delete notice

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
src/main/java/com/walkhub/walkhub/domain/user/domain/Badge.java
src/main/java/com/walkhub/walkhub/domain/user/domain/School.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryMyPageResponse.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryUserProfileResponse.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java

🔀 :: (#155) 필드명 변경 image->imageUrl

---

src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/UserAccountIdResponse.java
src/main/java/com/walkhub/walkhub/domain/user/service/SearchAccountIdService.java

🔀  :: (#162) search user accountId

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/QueryChallengeListResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListService.java

🔀 :: (#168) 챌린지 목록 보기 api

---

src/main/java/com/walkhub/walkhub/domain/school/exception/AgencyCodeNotMatchException.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/SchoolController.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/request/SchoolLogoRequest.java
src/main/java/com/walkhub/walkhub/domain/school/service/SchoolLogoSettingService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/School.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀  :: (#161) school logo image

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepository.java
src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
src/main/java/com/walkhub/walkhub/domain/school/domain/repository/SchoolRepository.java
src/main/java/com/walkhub/walkhub/domain/school/service/SchoolLogoSettingService.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/Group.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java

🔀 :: (#180) User Entity & User Repository 파일 위치 변경

---

src/main/java/com/walkhub/walkhub/global/security/FilterConfig.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#186) 토큰 필터 등록

---

src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/request/CreateNoticeRequest.java
src/main/java/com/walkhub/walkhub/domain/notice/service/CreateNoticeService.java

🔀 :: (#122) create notice

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/UserRankInfo.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepository.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java

🔀 :: (#185) 랭크 뷰 수정

---

src/main/java/com/walkhub/walkhub/global/querydsl/QuerydslConfig.java

🔀 :: (#191) JPAQueryFactory 빈 생성

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankInfo.java
src/main/java/com/walkhub/walkhub/domain/rank/job/SchoolRankJob.java

🔀 :: (#193) SchoolRankJob 수정

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/QueryChallengeDetailResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailService.java

🔀 :: (#173) 챌린지 상세 보기 api

---

.gitignore

🔀 :: (#196) DS_STORE .gitignore 추가

---

build.gradle
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
src/main/java/com/walkhub/walkhub/global/websocket/WebSocketConfig.java
src/main/java/com/walkhub/walkhub/global/websocket/exception/SocketExceptionListener.java
src/main/java/com/walkhub/walkhub/global/websocket/property/SocketProperty.java
src/main/resources/application.yml

🔀 :: (#199) Socket 설정

---

src/main/java/com/walkhub/walkhub/global/websocket/SocketRunner.java
src/main/java/com/walkhub/walkhub/global/websocket/WebSocketConfig.java
src/main/java/com/walkhub/walkhub/global/websocket/connect/WebSocketJwtHandler.java
src/main/java/com/walkhub/walkhub/global/websocket/property/ClientProperty.java

🔀 :: (#205) Socket.io Jwt 설정

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
src/main/java/com/walkhub/walkhub/domain/user/domain/Badge.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/infrastructure/image/DefaultImage.java

🔀 :: (#204) default 이미지 설정

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java

🔀 :: (#211) String -> LocalDate로 변경

---

src/main/java/com/walkhub/walkhub/global/error/ErrorResponse.java
src/main/java/com/walkhub/walkhub/global/error/ExceptionFilter.java
src/main/java/com/walkhub/walkhub/global/error/GlobalExceptionHandler.java
src/main/java/com/walkhub/walkhub/global/security/FilterConfig.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
src/main/java/com/walkhub/walkhub/global/websocket/exception/SocketExceptionListener.java

🔀 :: (#220) exception filter 추가

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java

🔀 :: (#219) birthday 삭제

---

src/main/java/com/walkhub/walkhub/domain/school/domain/repository/SchoolRepository.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/SchoolController.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SearchSchoolListResponse.java
src/main/java/com/walkhub/walkhub/domain/school/service/SearchSchoolService.java

🔀 :: (#217) search school

---

src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java

🔀 :: (#214) accountId 자리수 제한 추가

---

src/main/java/com/walkhub/walkhub/domain/cheering/exception/CanNotCheerMyselfException.java
src/main/java/com/walkhub/walkhub/domain/cheering/exception/SocketClientNotFoundException.java
src/main/java/com/walkhub/walkhub/domain/cheering/presentation/CheerController.java
src/main/java/com/walkhub/walkhub/domain/cheering/presentation/dto/request/CheerRequest.java
src/main/java/com/walkhub/walkhub/domain/cheering/presentation/dto/response/CheeringMessage.java
src/main/java/com/walkhub/walkhub/domain/cheering/service/CheeringService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
src/main/java/com/walkhub/walkhub/global/websocket/connect/WebSocketJwtHandler.java
src/main/java/com/walkhub/walkhub/global/websocket/exception/SocketExceptionListener.java

🔀 :: (#208) cheering api

---

src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#149) Security 설정 오류

---

src/main/java/com/walkhub/walkhub/domain/auth/presentation/AuthController.java

🔀 :: (#210) @RequestMapping 추가

---

src/main/java/com/walkhub/walkhub/domain/user/domain/GroupId.java

🔀 :: (#232) @Column(columnDefinition = "TINYINT") 추가

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/ExerciseAnalysis.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/SaveExerciseAnalysisRequest.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/SaveOrUpdateExerciseAnalysisService.java

🔀 :: (#72) ExerciseAnalysis 저장 api

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassCodeResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/RefreshClassCodeService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/Group.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#233) 반코드 재발급 api

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/exception/ClassCodeNotMatchException.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/JoinGroupRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/JoinGroupService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#229) add user number

---

src/main/java/com/walkhub/walkhub/domain/cheering/exception/UserNotExercisingException.java
src/main/java/com/walkhub/walkhub/domain/cheering/service/CheeringService.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepository.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#240) cheering add cheeringcount

---

src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
src/main/java/com/walkhub/walkhub/domain/school/domain/repository/SchoolRepository.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/SchoolController.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SearchSchoolListResponse.java
src/main/java/com/walkhub/walkhub/domain/school/service/SchoolLogoSettingService.java
src/main/java/com/walkhub/walkhub/domain/school/service/SearchSchoolService.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/DeleteClassService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/GroupRepository.java
src/main/java/com/walkhub/walkhub/domain/user/facade/GroupFacade.java
src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateSchoolInfoRequest.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/JoinGroupService.java
src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java

🔀 :: (#242) agencycode groupid

---

src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
src/main/java/com/walkhub/walkhub/domain/user/domain/Badge.java
src/main/java/com/walkhub/walkhub/domain/user/domain/Group.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java

🔀 :: (#246) BaseTimeEntity 추가

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/type/GoalType.java
src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
src/main/java/com/walkhub/walkhub/domain/notice/domain/type/Scope.java
src/main/java/com/walkhub/walkhub/domain/notice/service/CreateNoticeService.java
src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
src/main/java/com/walkhub/walkhub/domain/notification/domain/type/Type.java
src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/DeleteClassService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/domain/type/Sex.java
src/main/java/com/walkhub/walkhub/global/enums/Authority.java
src/main/java/com/walkhub/walkhub/global/enums/Scope.java

🔀 :: (#244) 타입이나 범위에 대한 코드 변경

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java

🔀 :: (#251) challenge 엔티티 다시 수정 

---

build.gradle
src/main/java/com/walkhub/walkhub/global/redis/EmbeddedRedisConfig.java
src/main/java/com/walkhub/walkhub/global/redis/RedisConfig.java
src/main/java/com/walkhub/walkhub/global/redis/properties/RedisProperties.java

 🔀 :: (#255) Redis 설정

---

src/main/java/com/walkhub/walkhub/domain/school/domain/repository/SchoolRepository.java
src/main/java/com/walkhub/walkhub/domain/su/presentation/SuController.java
src/main/java/com/walkhub/walkhub/domain/su/presentation/dto/response/SchoolListResponse.java
src/main/java/com/walkhub/walkhub/domain/su/service/ShowSchoolService.java

🔀 :: (#269) show school

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateGoalWalkCountRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/UpdateGoalWalkCountService.java

🔀 :: (#268) 하루 목표 걸음수 변경 API

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeListResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListService.java

🔀 :: (#278) 챌린지 목록 조회 api

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/CreateChallengeRequest.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/CreateChallengeService.java

🔀 :: (#277) create challenge

---

src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java

🔀 :: (#292) add authority

---

src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#261) security authority 세팅

---

build.gradle

🔀 :: (#295) redis error 해결

---

src/main/java/com/walkhub/walkhub/domain/notice/domain/type/Scope.java
src/main/java/com/walkhub/walkhub/domain/notice/service/CreateNoticeService.java
src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java

🔀 :; (#304) delete teacher scope

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
src/main/java/com/walkhub/walkhub/domain/challenge/facade/ChallengeFacade.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListService.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryParticipatedChallengeListService.java

🔀 :: (#297) 참여한 챌린지 목록 api

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java

🔀 :: (#288) 챌린지 참여 API

---

src/main/java/com/walkhub/walkhub/domain/user/domain/repository/CalorieLevelRepository.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/CalorieLevelListResponse.java
src/main/java/com/walkhub/walkhub/domain/user/service/CalorieLevelListService.java

🔀 :: (#289) show calorie level

---

build.gradle
src/main/java/com/walkhub/walkhub/WalkhubApplication.java
src/main/resources/application.yml
src/main/resources/ehcache.xml

🔀 :: (#322) 2차 캐시 설정

---

src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/BadgeRepository.java
src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepository.java
src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepositoryImpl.java
src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/vo/ClaimBadgeVO.java
src/main/java/com/walkhub/walkhub/domain/badge/presentation/BadgeController.java
src/main/java/com/walkhub/walkhub/domain/badge/presentation/dto/response/ClaimBadgeResponse.java
src/main/java/com/walkhub/walkhub/domain/badge/service/ClaimBadgeService.java

close #326 
Code Smell은 if처리 주석때문에 나는 것이니 신경쓰지 말아주세요!

🔀 :: (#326) send claim badge

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/request/TeacherCodeRequest.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/ConfirmTeacherCodeService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
src/main/java/com/walkhub/walkhub/global/exception/InvalidVerificationCodeException.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#309) 선생님 인증코드 확인 api

---

src/main/java/com/walkhub/walkhub/domain/notification/domain/repository/NotificationListRepository.java
src/main/java/com/walkhub/walkhub/domain/notification/presentation/NotificationController.java
src/main/java/com/walkhub/walkhub/domain/notification/presentation/dto/response/QueryNotificationListResponse.java
src/main/java/com/walkhub/walkhub/domain/notification/service/QueryNotificationListService.java

🔀 :: (#303) 알림 목록 보기 API

---

src/main/java/com/walkhub/walkhub/domain/school/facade/SchoolFacade.java
src/main/java/com/walkhub/walkhub/domain/su/presentation/SuController.java
src/main/java/com/walkhub/walkhub/domain/su/presentation/dto/response/CreateRootAccountResponse.java
src/main/java/com/walkhub/walkhub/domain/su/service/CreateRootAccountService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#338) create root account

---

src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/CalorieLevel.java
src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/repository/CalorieLevelRepository.java
src/main/java/com/walkhub/walkhub/domain/calorielevel/exception/CalorieLevelNotFoundException.java
src/main/java/com/walkhub/walkhub/domain/calorielevel/presentation/CalorieLevelController.java
src/main/java/com/walkhub/walkhub/domain/calorielevel/service/CalorieLevelListService.java
src/main/java/com/walkhub/walkhub/domain/calorielevel/service/UpdateMaxCalorieLevelService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#335) 칼로리 최대 레벨 설정 API

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/type/DateType.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/type/SchoolDateType.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/SchoolRankResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QuerySchoolRankService.java

🔀 :: (#132) 학교 랭킹 조회

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/DetailsClassResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryStudentCodeService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/Section.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
src/main/java/com/walkhub/walkhub/global/enums/Authority.java

🔀 :: (#346) show details class add teacher

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java

🔀 :: (#353) CustomChallengeRepository 이름 변경

---

.github/workflows/CD.yml

🔀 :: (#356) CD 파일 수정

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/DetailsClassResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/DetailsClassService.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryUserDetailsService.java

🔀 :: (#360) add details class

---

src/main/java/com/walkhub/walkhub/global/error/CustomAuthenticationEntryPoint.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#362) 403 에러 핸들링

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/SchoolController.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SchoolDetailsInfoResponse.java
src/main/java/com/walkhub/walkhub/domain/school/service/SchoolDetailsInfoService.java

🔀 :: (#364) 학교 상세보기 api (정보란)

---

src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/CreateChallengeRequest.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/UpdateChallengeRequest.java

🔀 :: (#374) FutureOrPresent 어노테이션 추가

---

src/main/java/com/walkhub/walkhub/domain/auth/presentation/AuthController.java
src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/request/CheckAccountIdRequest.java
src/main/java/com/walkhub/walkhub/domain/auth/service/CheckAccountIdExistsService.java

🔀 :: (#382) account-id 중복체크 API 추가

---

src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#376) securityConfig 설정

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryClosesChallengeService.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

* 대현이가 다 해놓아서 대부분 똑같아요 
* endAt 조건이 반대라서 수정했어요
* 중복코드를 줄였어요

🔀 :: (#365) 종료된 챌린지 목록 API

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/rank/facade/UserRankFacade.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListService.java

🔀 :: (#190) 다른 학교 유저 랭킹 조회하기

---

src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#391) class list

---

src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserAccessTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/ExerciseListResponse.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserDetailsResponse.java
src/main/resources/application.yml

🔀 :: (#387) JsonFormat으로 변경

---

src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepository.java
src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepositoryImpl.java
src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/vo/DefaultBadgeVO.java
src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/vo/MyBadgeVo.java
src/main/java/com/walkhub/walkhub/domain/badge/presentation/BadgeController.java
src/main/java/com/walkhub/walkhub/domain/badge/presentation/dto/response/QueryMyBadgeListResponse.java
src/main/java/com/walkhub/walkhub/domain/badge/service/ClaimBadgeService.java
src/main/java/com/walkhub/walkhub/domain/badge/service/QueryMyBadgeListService.java

🔀:: (#331) 자기 뱃지 목록 조회 API 

---

src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepository.java
src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/SaveOrUpdateExerciseAnalysisService.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java

🔀 :: (#394) Redis 적용하기

---

src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserAccessTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/ExerciseListResponse.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserDetailsResponse.java

🔀 :: (#405) DateFormat 변경

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java

🔀 :: (#403) 반 탈퇴  시 챌린지 탈퇴

---

src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
src/main/java/com/walkhub/walkhub/domain/badge/service/QueryUserBadgeListService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/exception/DefaultTitleBadgeNotFound.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#399) 회원가입시 기본뱃지 설정, 예약어 변경등

---

src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepository.java
src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java

🔀 :: (#401) 공지사항 보기 페이징추가

---

src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

반을 가입할 때 USER이외의 권한이 반 가입이 되면 반 리스트를 불러올 때 500이 떠서 수정했습니다.
close #411

🔀 :: (#411) authenticated() -> hasAuthority("USER")로 수정

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/SchoolListResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QuerySchoolRankService.java
src/main/java/com/walkhub/walkhub/domain/rank/service/SchoolSearchService.java
src/main/java/com/walkhub/walkhub/domain/school/service/SchoolDetailsInfoService.java

중복되는부분이 많아 한 pr에 올립니다
close #178 
close #396

🔀 :: (#178, #396) 학교검색 api, npe해결

---

src/main/java/com/walkhub/walkhub/domain/calorielevel/service/CalorieLevelListService.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#413) 칼로리 레벨 리스트 securityConfig설정

---

src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java

🔀 :: (#409) 유저 전체 리스트 리팩토링

---

src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/SectionRepository.java

🔀 :: (#420) 반 생성할 때 예외 처리

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/request/UserSearchRequest.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/UserSearchForTeacherService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java

close #416 
#272 랑 로직이 비슷해서 병합할까하다가 그냥 하나 더 만들었는데 의견 자유롭게 주시면 감사하겠습니다!

🔀 :: (#416) 유저 검색 API (선생님용)

---

src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#424) 유저 검색 선생님용 403 해결

---

src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#424) 유저 검색 선생님용 버그 재수정

---

src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserAccessTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/auth/service/TokenRefreshService.java
src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/ExerciseListResponse.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankId.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserDetailsResponse.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
src/main/java/com/walkhub/walkhub/global/date/DateTimeZoneConfiguration.java
src/main/java/com/walkhub/walkhub/global/entity/BaseTimeEntity.java

🔀 :: (#430) Timezone 설정 추가

---

src/main/java/com/walkhub/walkhub/domain/notice/service/DeleteNoticeService.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

code smell은 TEACHER를 상수로 만들어달라는 것이니 신경 쓰지 않아도 됩니다...
close #428

🔀 :: (#428) securityConfig 설정 추가

---

src/main/java/com/walkhub/walkhub/domain/teacher/service/ConfirmTeacherCodeService.java

🔀 :: (#432) 선생님 인증 API 수정

---

src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserAccessTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/ExerciseListResponse.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserDetailsResponse.java

🔀 :: (#439) DateTimeFormat 변경

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/LocationRepository.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseDetailsResponse.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseDetailsService.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#436) 운동 기록 상세보기API

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassListResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java

🔀 :: (#434) 선생님 목록 API 수정

---

src/main/java/com/walkhub/walkhub/global/entity/BaseTimeEntity.java

🔀 :: (#446) BaseTimeEntity 수정

---

src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#448) 오타 수정

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassListResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java

🔀 :: (#444) Section 목록에서 반 없는 선생님도 보여주도록 변경

---

src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java

close #442 
코드가 더 난해해진 거 같기도 하고.. 의견 많이 내주세요

🔀 :: (#442) 우리 학교 유저 랭킹 리팩토링

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/UserRank.java
src/main/java/com/walkhub/walkhub/domain/rank/job/UserRankJob.java
src/main/java/com/walkhub/walkhub/domain/rank/job/constant/RankJobConstant.java

🔀 :: (#438) user rank job constant로 리팩토링

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/InputHealthInformationRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java

🔀 :: (#453) 건강 정보 수정 API 성별 추가

---

src/main/java/com/walkhub/walkhub/global/websocket/connect/WebSocketJwtHandler.java

클라이언트 분들에 부탁으로 임시로 했습니다!
close #467

🔀 :: (#467) 임시 로그 설정

---

src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#463) 권한 수정

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java

🔀 :: (#469) 쿼리 버그 수정

---

src/main/java/com/walkhub/walkhub/domain/rank/facade/UserRankFacade.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/OtherSchoolUserRankListResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/OurSchoolUserRankListResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListService.java

🔀 :: (#474) 다른학교 유저 랭킹 dto 분리

---

src/main/java/com/walkhub/walkhub/domain/rank/scheduler/SchoolRankScheduler.java

🔀 :: (#476) school rank job 크론 주기

---

src/main/java/com/walkhub/walkhub/domain/cheering/service/CheeringService.java

🔀 :: (#488) CheeringService log 설정

---

src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java

🔀 :: (#480) user rank 파라미터 수정

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java

🔀 :: (#472) where문 추가

---

src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java

프론트 님의 요청에 따라 챌린지 작성자의 권한, 학교, 반, 번호까지 주게됐습니다.
close #477

🔀 :: (#477) 챌린지 상세보기 수정

---

src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/repository/CalorieLevelRepository.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseDetailsResponse.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseDetailsService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryUserProfileResponse.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java

마이페이지, 유저페이지 section npe
회원가입시 최대칼로리레벨 1 default
회원가입시 sex nullable, default x로
order인거 sequence로
기록측정시작 goalType notnull
기록측정시작 goal default로
close #459

🔀 :: (#459) 명세 따라 자잘한 수정

---

src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java

🔀 :: (#486) 챌린지 참여 시 NPE

---

src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryUserProfileResponse.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java

🔀 :: (#493) school_image_url 추가

---

src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/repository/CalorieLevelRepository.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsService.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseDetailsResponse.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseDetailsService.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankId.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java

🔀 :: (#503) 날라간 pr 복구, zonedDateTime 에러

---

src/main/java/com/walkhub/walkhub/domain/rank/service/QuerySchoolRankService.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListService.java
src/main/java/com/walkhub/walkhub/domain/rank/service/SchoolSearchService.java
src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java

🔀 :: (#505) /rank api 수정

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/FinishExerciseService.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExercisingUserListService.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java

🔀 :: (#506) 운동 API

---

src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryGoalWalkCountResponse.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryGoalWalkCountService.java

🔀 :: (#511) 하루 목표 걸음수 조회 api

---

src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java

🔀 :: (#501) 운동 분석 결과 출력 API

---

src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java

🔀 :: (#515) QueryExerciseAnalysisList

---

src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseAnalysisResponse.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java

🔀 :: (#517) 운동한 시간 컬럼

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassListResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java

🔀 :; (#520) 반 리스트 보여주기에서 userCount 추가

---

src/main/java/com/walkhub/walkhub/domain/notification/presentation/NotificationController.java

🔀 :: (#556) fcm exception 처리 변경 

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java

🔀 :: (#560) number columnDefinition 수정

---

src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java

🔀 :: (#558) 변수명 변경, 영속성 컨텍스트 로직 삭제

---

src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryUserProfileResponse.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java

🔀 :: (#563) 마이페이지 API 수정

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepository.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseListService.java

close #565
querystring int받는걸 개선해야할것같은데 어케하는게 좋을까요?

🔀 :: (#565) 운동기록 리스트 Api 페이지

---

src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java

🔀 :: (#569) 건강정보 수정 if문 삭제

---

src/main/java/com/walkhub/walkhub/domain/image/presentation/ImageController.java

🔀 :: (#572) key값 안넣었을 때 에러 처리

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/DetailsClassResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/DetailsClassService.java

🔀 :: (#575) 반 상세보기 Response

---

src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustomImpl.java

🔀 :: (#577) 공지사항 보기 api

---

src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepositoryImpl.java
src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java

🔀 :: (#581) Custom Repository에 @Repository 제거

---

src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java

🔀 :: (#583) @Repository 어노테이션 추가

---

.github/CODEOWNERS

🔀 :: (#604) CODEWOENRS 변경 

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/HealthResponse.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserHealthService.java

🔀 :: (#590) 건강 정보 조회 Api

---

src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseDetailsResponse.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseDetailsService.java

🔀 :: (#598) 위치 가져오기 Api Response 변경

---

src/main/java/com/walkhub/walkhub/domain/auth/presentation/AuthController.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyInformationService.java

🔀 :: (#608) Controller에 추가

---

src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/request/ModifyNoticeRequest.java
src/main/java/com/walkhub/walkhub/domain/notice/service/ModifyNoticeService.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#597) 공지사항 수정 API

---

src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java

🔀 :: (#614) 유저 검색 선생님용 API 수정

---

src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java

🔀 :: (#618) NPE 설정

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/SchoolRankResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryMySchoolRankService.java

🔀 :: (#621) 내 학교 랭킹 조회 API 수정

---

src/main/java/com/walkhub/walkhub/domain/teacher/facade/TeacherFacade.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassListResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryMyClassService.java

🔀 :: (#600) 내 클래스 조회 Api 추가

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ManageTeachersResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/ManageTeacherService.java

close #586 
퍼사드 덕분에 코드를 굉장히 많이 줄였네요!

🔀 :: (#586) 선생님 관리 API

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/vo/ChallengeDetailsForTeacherVO.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/ChallengeParticipantRequest.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeParticipantListResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantListService.java

close #613 
주석은 머지하기 전에 다 지울예정 입니다.
private method도 머지되기 전에 지우겠습니다.
(지우는 것이 맞는지 몰라서 아직 두고 있습니다).

🔀 :: (#613) 챌린지 참여자 목록 보기 Api

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SchoolDetailsInfoResponse.java
src/main/java/com/walkhub/walkhub/domain/school/service/SchoolDetailsInfoService.java

🔀 :: (#636) Response값 userCount -> totalUserCount로 수정

---

src/main/java/com/walkhub/walkhub/domain/notification/domain/type/Type.java
src/main/java/com/walkhub/walkhub/domain/notification/presentation/NotificationController.java
src/main/java/com/walkhub/walkhub/domain/notification/presentation/dto/request/SubscribeRequest.java
src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
src/main/java/com/walkhub/walkhub/infrastructure/fcm/FirebaseNotification.java

🔀 :: (#585) fcm error handling 

---

src/main/java/com/walkhub/walkhub/domain/su/exception/SchoolRootUserExistsException.java
src/main/java/com/walkhub/walkhub/domain/su/service/CreateRootAccountService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#640) create root error

---

src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/CalorieLevel.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRank.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/UserRank.java
src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
src/main/java/com/walkhub/walkhub/domain/user/domain/Section.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java

🔀 :: (#641) @Cacheable 어노테이션 추가

---

src/main/java/com/walkhub/walkhub/domain/auth/service/CheckAuthCodeExistsService.java

🔀 :: (#649) 전화번호 인증 로직 변경

---

src/main/resources/createProcedures.sql

🔀 :: (#651) spring boot 실행 시 procedure 생성 sql 수정

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SchoolDetailsInfoResponse.java
src/main/java/com/walkhub/walkhub/domain/school/service/SchoolDetailsInfoService.java

🔀 :: (#655) 학교 상세보기 Api 수정

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/QueryExerciseHistoryRequest.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#659) 운동기록 보기(선생님용) Api 수정

---

src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsForTeacherResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsForTeacherService.java

close #661 
챌린지 상세보기 에서 자기 챌린지이면 true, 아니면 false로 Response 반환

🔀 :: (#661) 챌린지 상세보기(웹) Api 수정

---

src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsForStudentResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsForStudentService.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java

🔀 :: (#665) 현재 걸음 수 & 거리 추가

---

src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java

🔀 :: (#667) 챌린지 목록 보기(웹) url 변경 

---

src/main/java/com/walkhub/walkhub/domain/auth/domain/repository/RefreshTokenRepository.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
src/main/java/com/walkhub/walkhub/domain/user/service/LogoutService.java
src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java

🔀 :: (#669) Log out API

---

src/main/java/com/walkhub/walkhub/domain/rank/facade/UserRankFacade.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListByMySchoolResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListResponse.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java

🔀 :: (#673) dto분리작업

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryMySchoolRankService.java
src/main/java/com/walkhub/walkhub/global/error/ExceptionFilter.java

🔀 :: (#675) 내 학교 정보 조회(앱) 변경 

---

src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java

🔀 :: (#679) 회원가입 API Request 수정

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
src/main/java/com/walkhub/walkhub/domain/challenge/facade/ChallengeFacade.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/CreateChallengeService.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsForTeacherService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/User.java

🔀 :: (#671) 명세대로 수정

---

src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/CreateChallengeResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/CreateChallengeService.java

🔀 :: (#685) 챌린지 생성 시 Response값 수정

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/DetailsClassResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/DetailsClassService.java
src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java

🔀 :: (#687) userCount 추가

---

src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java

🔀 :: (#692) scope 추가

---

src/main/java/com/walkhub/walkhub/domain/notification/presentation/dto/response/QueryNotificationListResponse.java
src/main/java/com/walkhub/walkhub/domain/notification/service/QueryNotificationListService.java
src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
src/main/java/com/walkhub/walkhub/infrastructure/fcm/FirebaseNotification.java

🔀 :: (#689) 알림 목록 API 수정 

---

src/main/java/com/walkhub/walkhub/domain/auth/domain/RefreshToken.java
src/main/java/com/walkhub/walkhub/domain/auth/service/TokenRefreshService.java

🔀 :: (#695) Refresh Token 발급 시 만료 시간 설정

---

src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/CalorieLevel.java
src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/CreateChallengeRequest.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/CreateExerciseService.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/FinishExerciseService.java
src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationList.java
src/main/java/com/walkhub/walkhub/domain/school/domain/School.java

🔀 :: (#697) Entity에 Default Value 적용 오류

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsForStudentResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsForStudentService.java

🔀 :: (#706) 챌린지 목록 조회(앱) 쿼리

---

src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java

🔀 :: (#711) 공지사항 보기 페이징 처리

---

src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/request/UserSearchRequest.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/UserSearchForTeacherService.java

🔀 :: (#714) 유저 검색 Api request에 validation option 추가

---

src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java

🔀 :: (#719) buildSortCondition 적용 안됨 오류 해결

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeListForTeacherResponse.java
src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListForTeacherService.java

🔀 :: (#709) 챌린지 목록 보기(웹) resopnse

---

src/main/java/com/walkhub/walkhub/domain/teacher/facade/TeacherFacade.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassResponse.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/ManageTeacherService.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryClassListService.java

🔀 :: (#710) 선생님 관리 Api

---

src/main/java/com/walkhub/walkhub/domain/auth/exception/PhoneNumberMatchedException.java
src/main/java/com/walkhub/walkhub/domain/auth/service/CheckAuthCodeExistsService.java
src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java

🔀 :: (#723) 중복전화번호 입력시 409 에러

---

src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java

🔀 :: (#730) 챌린지 참여 시 500 에러

---

src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java

🔀 :: (#678) 하루 운동 저장 API 수정

---

src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
src/main/java/com/walkhub/walkhub/global/exception/ImageValueNotFoundException.java
src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Facade.java

close #728 
버그는 아니지만 서버에서 밑에 WARN을 발생시켜서 추가했습니다!
No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.

🔀 :: (#728) objectMetadata 추가 & error 처리

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRank.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankId.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SchoolDetailsInfoResponse.java
src/main/java/com/walkhub/walkhub/domain/school/service/SchoolDetailsInfoService.java

🔀 :: (#733) 학교 상세보기 Api 500 해결

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/rank/service/SchoolSearchService.java

🔀 :: (#735) 학교 랭킹 조회 및 검색 Api 500 해결

---

src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustomImpl.java

🔀 :: (#744) 챌린지 목록 보기(앱) Api 500 해결

---

src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseHistoryResponse.java
src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseHistoryService.java

🔀 :: (#737) 운동 기록 보기(선생님용) 총 페이지 개수 추가

---

src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyInformationService.java
src/main/java/com/walkhub/walkhub/domain/user/service/UpdateUserInfoService.java

🔀 :: (#748) 학교 변경 후 내 정보 보기 호출 시 school이 null로 뜸

---

src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java

🔀 :: (#750) 우리학교 유저 랭킹 조회 Api 500 해결

---

src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java

🔀 :: (#753) TodayRank이 null이면 ranking & walkCount 0처리

---

src/main/java/com/walkhub/walkhub/domain/exercise/facade/ExerciseAnalysisFacade.java

🔀 :: (#755) [선생님] 유저 상세보기 API 응답값

---

src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepositoryCustom.java
src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepositoryCustomImpl.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListService.java

🔀 :: (#757) 우리학교 유저 랭킹 조회 Api 500해결

---

src/main/java/com/walkhub/walkhub/domain/su/service/CreateRootAccountService.java
src/main/java/com/walkhub/walkhub/domain/su/service/UpdateSchoolPasswordService.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
src/main/java/com/walkhub/walkhub/domain/teacher/service/GenerateVerificationCodeService.java
src/main/java/com/walkhub/walkhub/domain/user/service/UserAuthCodeService.java
src/main/java/com/walkhub/walkhub/global/utils/code/RandomCodeUtil.java

🔀 :: (#759) 랜덤 난수 생성 & 반 생성하기 Api 수정

---

src/main/java/com/walkhub/walkhub/global/security/jwt/JwtTokenProvider.java

🔀 :: (#761) Jwt ExpiredJwtException import 수정
